version: 2
updates:
  # GitHub Actions dependencies (grouped)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 10
    groups:
      all-actions:
        patterns:
          - "*"

  # pip dependencies (grouped)
  - package-ecosystem: "pip"
    directory: "/src/ContentProcessorAPI"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 10
    groups:
      all-pip-deps:
        patterns:
          - "*"

  # npm dependencies (grouped)
  - package-ecosystem: "npm"
    directory: "/src/ContentProcessorWeb"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "build"
    target-branch: "dependabotchanges"
    open-pull-requests-limit: 10
    groups:
      all-npm-deps:
        patterns:
          - "*"